name: Java Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Xvfb
        run: sudo apt-get install xvfb

      - name: Run tests with virtual display
        run: xvfb-run mvn test

      - name: Load environment variables
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Using .env.test"
            cp .env.test .env
          elif [ -f .env.production ]; then
            echo "Using .env.production"
            cp .env.production .env
          else
            echo ".env file already exists, skipping copy"
          fi

      - name: Build and Test
        run: mvn clean verify
        env:
          DISPLAY: ":99"

      - name: Upload JaCoCo Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
